---
- name: "Download filebeat's deb"
  get_url:
    url: "https://artifacts.elastic.co/downloads/filebeat/filebeat-{{ elk_stack_version }}-amd64.deb"
    dest: "files/filebeat-{{ elk_stack_version }}-amd64.deb"
  delegate_to: localhost
  register: download_filebeat
  until: download_filebeat is succeeded
  when: elastic_install_type == 'remote'
- name: Copy filebeat to manage host
  copy:
    src: "files/filebeat-{{ elk_stack_version }}-amd64.deb"
    mode: 0755
    dest: "/tmp/filebeat-{{ elk_stack_version }}-amd64.deb"
