version: '3.9'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    volumes:
      - ./pg_project:/var/lib/postgresql/data
      - ./pg_backup:/tmp/pg_backup
    ports:
      - "${POSTGRES_PORT:-5433}:5432"