all:
  hosts:
    master:
      ansible_host: 51.250.102.228
      ip: 10.129.0.24
      access_ip: 10.129.0.24
    node1:
      ansible_host: 51.250.106.119
      ip: 10.129.0.13
      access_ip: 10.129.0.13
    node2:
      ansible_host: 84.201.142.112
      ip: 10.129.0.27
      access_ip: 10.129.0.27
    node3:
      ansible_host: 84.252.136.153
      ip: 10.129.0.7
      access_ip: 10.129.0.7
    node4:
      ansible_host: 84.201.162.126
      ip: 10.129.0.6
      access_ip: 10.129.0.6
  children:
    kube-master:
      hosts:
        master:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        master:
        node1:
        node2:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}